name: Obsidian Vault Sync

on:
  push:
    branches:
      - main  # Or specify another branch to trigger on push

jobs:
  sync-vault:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VAULT_PATH: ./vault  # Path to your Obsidian vault folder in the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xxhash openai psycopg2 pgvector

      - name: Run Vault Sync Script
        run: python sync_vault.py
